Repository nektos/act, pull requests merged in 2021-08, with the labels that each got.

#762 README: add MacPorts info
  README.md
Labels: size/XS

#761 Fix `ImageOS` format
  pkg/runner/run_context.go
Labels: size/XS

#719 Read local actions from docker container
  pkg/container/docker_build.go
  pkg/container/docker_run.go
  pkg/runner/step_context.go
  pkg/runner/testdata/basic/push.yml
  pkg/runner/testdata/parallel/push.yml
  pkg/runner/testdata/uses-composite/push.yml
Labels: size/M, stale-exempt

#752 Fix format function {{, }} are escapes
  pkg/runner/expression.go
  pkg/runner/expression_test.go
Labels: size/M

#763 Simplify Matrix decode, add defaults for fail-fast and max-parallel, add test
  pkg/model/testdata/strategy/push.yml
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/expression_test.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
Labels: stale-exempt, size/L

#766 Update docs, file formatting and docker images
  .editorconfig
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/actions/choco/action.yml
  .github/actions/composite/action.yml
  .github/actions/composite/script.sh
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .gitignore
  .mergify.yml
  .prettierignore
  .prettierrc.yml
  .vscode/extensions.json
  .vscode/settings.json
  CONTRIBUTING.md
  IMAGES.md
  LICENSE
  Makefile
  README.md
  cmd/root.go
  codecov.yml
Labels: size/L

#767 Fix docker: invalid reference format
  pkg/runner/step_context.go
  pkg/runner/testdata/local-action-dockerfile/push.yml
  pkg/runner/testdata/localdockerimagetest_/Dockerfile
Labels: size/XS

#772 Add proper support for working-directory & fix command builder
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
  pkg/runner/testdata/basic/push.yml
  pkg/runner/testdata/dir with spaces/push.yml
  pkg/runner/testdata/workdir/push.yml
Labels: size/L

#774 fix: copy whole action dir to container
  pkg/runner/step_context.go
Labels: needs-work, size/S

#786 Improve `--list`
  cmd/list.go
  pkg/model/planner.go
  pkg/model/workflow.go
Labels: size/M

#787 Update Go to 1.17
  .github/workflows/checks.yml
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: size/S

#768 Cache dockerhub images from linux for macOS
  .github/workflows/checks.yml
Labels: size/M
