Repository nektos/act, pull requests merged in 2021-11, with the labels that each got.

#860 ci: remove macOS tests
  .github/workflows/checks.yml
  .mergify.yml
Labels: size/L

#856 Fixes
  pkg/container/docker_build.go
  pkg/container/docker_logger.go
Labels: size/XS

#862 ci(mergify): fix deprecated strict mode
  .mergify.yml
Labels: size/S

#677 Asset server implementation
  README.md
  cmd/input.go
  cmd/root.go
  go.mod
  go.sum
  pkg/artifacts/server.go
  pkg/artifacts/server_test.go
  pkg/artifacts/testdata/upload-and-download/artifacts.yml
  pkg/common/outbound_ip.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/testdata/actions/node12/.gitignore
Labels: stale-exempt, size/XL

#870 ci(golangci-lint): switch to latest
  .github/workflows/checks.yml
  .golangci.yml
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
Labels: size/S

#859 feat: allow existing logger from context
  pkg/runner/logger.go
Labels: size/XS

#872 fix: interpolate env for step actions
  pkg/runner/step_context.go
  pkg/runner/testdata/actions/docker-local/action.yml
  pkg/runner/testdata/actions/docker-local/entrypoint.sh
  pkg/runner/testdata/local-action-dockerfile/push.yml
Labels: size/S

#873 fix: cleanup unused actions
  .github/actions/composite/action.yml
  .github/actions/composite/script.sh
Labels: size/S

#871 Fix github SSH regex for missing .git extension
  pkg/common/git.go
  pkg/common/git_test.go
Labels: size/XS

#877 fix: use docker lib for image ref parsing
  go.mod
  pkg/container/docker_pull.go
  pkg/container/docker_pull_test.go
Labels: size/S

#876 fix: correctly unmarshal entrypoint
  pkg/model/action.go
  pkg/runner/step_context.go
  pkg/runner/testdata/actions/docker-url/action.yml
Labels: size/S

#883 fix: fromJSON should work with any JSON
  pkg/runner/expression.go
  pkg/runner/expression_test.go
Labels: size/XS

#886 docs: add brew installation from HEAD
  README.md
Labels: size/XS

#890 Revert "feat: allow existing logger from context"
  pkg/runner/logger.go
Labels: size/XS

#893 Fix regex for GITHUB_ENV parsing
  pkg/container/docker_run.go
  pkg/runner/testdata/env-and-path/push.yaml
Labels: size/S

#894 Don't interpolate joboutputs, before job is done
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/outputs/push.yml
Labels: size/M

#878 feat: add option for docker image rebuild
  README.md
  cmd/input.go
  cmd/root.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: size/S

#903 ci(choco): fix chocolatey docker build
  .github/actions/choco/Dockerfile
  .github/actions/choco/entrypoint.sh
Labels: size/M

#906 feat: SELinux lables for --bind
  go.mod
  go.sum
  pkg/runner/run_context.go
Labels: size/XS

#898 feat: allow existing logger from context
  pkg/common/testflag.go
  pkg/runner/logger.go
Labels: size/S

#887 Add more steps context support
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/steps-context/conclusion/push.yml
  pkg/runner/testdata/steps-context/outcome/push.yml
Labels: size/L

#868 container credentials
  Makefile
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/run_context.go
Labels: size/M

#891 Docker auth
  go.sum
  pkg/container/docker_auth.go
  pkg/container/docker_pull.go
  pkg/container/docker_pull_test.go
  pkg/container/testdata/docker-pull-options/config.json
Labels: size/M
