Repository nektos/act, pull requests merged in 2021-12, with the labels that each got.

#911 Fix and test choco action
  .editorconfig
  .github/actions/choco/Dockerfile
  .github/actions/choco/action.yml
  .github/actions/choco/entrypoint.sh
  .github/workflows/checks.yml
  .github/workflows/release.yml
Labels: size/M

#840 fix: continue jobs + steps after failure
  pkg/common/executor.go
  pkg/common/job_error.go
  pkg/model/planner.go
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/testdata/if-expressions/push.yml
  pkg/runner/testdata/job-status-check/push.yml
Labels: size/XL

#920 fix: ::stop-commands:: should continue to print the lines
  pkg/runner/command.go
  pkg/runner/command_test.go
Labels: size/S

#924 ci(Mergify): configuration update
  .mergify.yml
Labels: size/XS

#929 fix: clarify --reuse and --rm flags
  .editorconfig
  README.md
  cmd/root.go
Labels: size/S

#930 fix: rework setupShellCommand
  .editorconfig
  pkg/model/workflow_test.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/shells/bash/push.yml
  pkg/runner/testdata/shells/custom/push.yml
  pkg/runner/testdata/shells/pwsh/push.yml
  pkg/runner/testdata/shells/python/push.yml
  pkg/runner/testdata/shells/sh/push.yml
Labels: size/L

#923 ci: replace superlinter with megalinter
  .editorconfig
  .github/dependabot.yml
  .github/linters/.golangci.yml
  .github/linters/.markdown-lint.yml
  .github/workflows/checks.yml
  .gitignore
  .golangci.yml
  .goreleaser.yml
  .markdownlint.yml
  .mega-linter.yml
  Makefile
  pkg/container/docker_run.go
  pkg/runner/expression.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
Labels: size/L

#938 lint(megalinter): disable markdown link check
  .mega-linter.yml
Labels: size/XS

#793 Feature: uses in composite
  pkg/model/action.go
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/actions/docker-local-noargs/Dockerfile
  pkg/runner/testdata/actions/docker-local-noargs/action.yml
  pkg/runner/testdata/actions/docker-local-noargs/entrypoint.sh
  pkg/runner/testdata/local-action-dockerfile/push.yml
  pkg/runner/testdata/local-action-via-composite-dockerfile/action.yml
  pkg/runner/testdata/local-action-via-composite-dockerfile/push.yml
  pkg/runner/testdata/uses-composite-with-error/composite_action2/action.yml
  pkg/runner/testdata/uses-composite-with-error/push.yml
  pkg/runner/testdata/uses-composite/composite_action/action.yml
  pkg/runner/testdata/uses-composite/push.yml
  pkg/runner/testdata/uses-nested-composite/composite_action2/action.yml
  pkg/runner/testdata/uses-nested-composite/push.yml
Labels: stale-exempt, size/XL

#931 refactor: export and move shared contexts into pkg/model
  pkg/model/github_context.go
  pkg/model/job_context.go
  pkg/model/step_result.go
  pkg/runner/command_test.go
  pkg/runner/expression_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
Labels: size/L

#937 fix: update install.sh
  install.sh
Labels: size/M
