Repository nektos/act, pull requests merged in 2021-06, with the labels that each got.

#716 Add support for container kernel capabilities
  cmd/input.go
  cmd/root.go
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: size/S

#722 fix: update issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/linters/.markdown-lint.yml
  .markdownlint.yml
Labels: size/M

#700 Switch to `interface{}` instead of `map[string]...`
  pkg/model/workflow.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
Labels: size/M

#725 fix: don't replace empty secrets
  pkg/runner/logger.go
Labels: size/XS

#727 fix: update codecov action
  .github/workflows/checks.yml
Labels: needs-work, size/XS

#731 fix: update codecov action (again)
  .github/workflows/checks.yml
Labels: needs-work, size/XS

#726 fix: wrong perms
  pkg/runner/run_context.go
Labels: needs-work, size/XS

#714 Support container removal at exit. Fixes #694
  cmd/input.go
  cmd/root.go
  pkg/runner/runner.go
Labels: size/S

#712 Refactor local, composite actions and run steps
  pkg/runner/step_context.go
  pkg/runner/testdata/local-action-docker-url/push.yml
  pkg/runner/testdata/local-action-dockerfile/push.yml
  pkg/runner/testdata/local-action-js/push.yml
Labels: size/M

#681 Test fixups for Windows/Forks
  pkg/runner/run_context_test.go
Labels: size/XS, stale

#723 Update images, fix extrapath
  IMAGES.md
  README.md
  cmd/platforms.go
  cmd/root.go
  pkg/common/git.go
  pkg/container/docker_images_test.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/testdata/actions/docker-local/Dockerfile
  pkg/runner/testdata/actions/docker-url/action.yml
  pkg/runner/testdata/basic/push.yml
  pkg/runner/testdata/commands/push.yml
  pkg/runner/testdata/fail/push.yml
  pkg/runner/testdata/job-container-non-root/push.yml
  pkg/runner/testdata/job-container/push.yml
  pkg/runner/testdata/parallel/push.yml
  pkg/runner/testdata/shells/bash/push.yml
  pkg/runner/testdata/shells/pwsh/push.yml
  pkg/runner/testdata/shells/python/push.yml
  pkg/runner/testdata/shells/sh/push.yml
  pkg/runner/testdata/uses-docker-url/push.yml
Labels: size/L

#743 fix: warn Apple M1 (arm64) users
  cmd/root.go
  pkg/runner/command_test.go
Labels: size/S
