Repository nektos/act, pull requests merged in 2021-03, with the labels that each got.

#585 add codecov integration
  .github/workflows/push.yml
  .gitignore
Labels: size/S

#563 Add code testing on MacOS
  .github/workflows/push.yml
Labels: meta/needs-work, size/L

#577 Fix platforms during initial setup
  cmd/root.go
Labels: meta/needs-work, size/S

#575 Update Shell Tasks to match ScriptHandlerHelpers
  pkg/model/workflow.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/powershell/push.yml
Labels: meta/needs-work, size/M

#591 use container image platform only on docker 1.41+
  README.md
  cmd/root.go
  go.mod
  go.sum
  pkg/container/docker_run.go
Labels: size/M
