Repository nektos/act, pull requests merged in 2021-09, with the labels that each got.

#797 feat: add Dependabot config
  .github/dependabot.yml
Labels: size/S

#791 Refresh hash after pull for branch refs
  pkg/common/git.go
Labels: size/XS

#809 support for container option: --hostname
  go.mod
  go.sum
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/container-hostname/push.yml
Labels: size/M

#815 Provide hint for -P
  pkg/runner/run_context.go
Labels: size/XS

#821 Remove ubuntu-16.04 and add missing links for nix/go
  IMAGES.md
  README.md
  cmd/platforms.go
  cmd/root.go
Labels: size/M

#776 fix: mount volume for workflow info
  pkg/runner/run_context.go
  pkg/runner/testdata/actions/docker-local/entrypoint.sh
  pkg/runner/testdata/local-action-dockerfile/push.yml
Labels: stale-exempt, size/XS

#822 Bump all dependencies (and fix dependabot mess)
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  go.mod
  go.sum
Labels: size/S

#825 ci: pin goreleaser version
  .github/workflows/checks.yml
  .github/workflows/release.yml
Labels: size/XS

#810 fix(mergify): needs-work label handling
  .mergify.yml
Labels: needs-work, size/XS

#823 fix: add simple concurrency limit
  pkg/runner/runner.go
Labels: size/S

#771 Add reading environment from Docker image
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
Labels: size/M

#830 refactor: re-implement `embed` without "unused" import
  .gitignore
  pkg/runner/step_context.go
Labels: size/S

#828 fix: rewrite how image env is merged
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/container/testdata/Dockerfile
  pkg/runner/run_context.go
  pkg/runner/step_context.go
Labels: size/L

#832 fix: rewrite StepContext env
  pkg/runner/step_context.go
  pkg/runner/testdata/local-action-dockerfile/push.yml
Labels: size/XS
