Repository nektos/act, pull requests merged in 2021-04, with the labels that each got.

#593 Return error if both `run` an `uses` are specified in one step
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/testdata/uses-and-run-in-one-step/push.yml
Labels: size/M

#594 Remove HOME environment variable
  pkg/runner/run_context.go
Labels: size/XS

#514 Add support for composite actions
  .github/actions/composite/action.yml
  .github/actions/composite/script.sh
  .github/workflows/test-composite.yml
  pkg/model/action.go
  pkg/model/workflow.go
  pkg/runner/command.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/uses-composite/composite_action/action.yml
  pkg/runner/testdata/uses-composite/push.yml
Labels: meta/needs-work, size/L

#601 Go 1.16 is required since 5752a03dc
  README.md
Labels: size/XS

#600 Refactor `.actrc` locations and default image survey
  cmd/root.go
  go.mod
  go.sum
  pkg/runner/run_context.go
Labels: size/L

#606 Handle tagless versions
  Makefile
Labels: size/XS

#595 Clean the repository cache if it is in incomplete state
  pkg/common/executor.go
  pkg/common/executor_test.go
  pkg/common/git.go
Labels: size/M

#624 Add nektos/act to awesome-runner list
  README.md
Labels: size/XS
