Repository nektos/act, pull requests merged in 2021-05, with the labels that each got.

#643 feat: Speeding up workflows
  .github/workflows/push.yml
Labels: size/M

#619 fix: rework container architecture flag
  README.md
  cmd/root.go
  pkg/container/docker_images.go
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
Labels: size/L, stale-exempt

#633 Prefer go-git to find the reference name
  pkg/common/git.go
Labels: size/M

#537 Add option to allow files/directories in `.gitignore` to be copied to container
  README.md
  cmd/input.go
  cmd/root.go
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: meta/needs-work, size/M

#630 fix: update readme with more relevant/updated information
  IMAGES.md
  README.md
Labels: size/L

#620 feat: Don't push `pkg/runner/act/` where actions cache is stored
  .gitignore
Labels: size/XS

#605 GitHub Event Path #542
  pkg/runner/run_context.go
Labels: size/S

#654 fix: ignore `act` binary built when using `make`
  .gitignore
Labels: size/XS

#637 Fixes Issue #597
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/issue-597/spelling.yaml
Labels: meta/needs-work, size/M

#650 Add `super-linter` + fix lint issues
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/linters/.golangci.yml
  .github/linters/.markdown-lint.yml
  .github/workflows/push.yml
  .golangci.yml
  .vscode/settings.json
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/graph.go
  pkg/common/file.go
  pkg/common/git.go
  pkg/common/git_test.go
  pkg/container/docker_build.go
  pkg/container/docker_pull.go
  pkg/container/docker_run.go
  pkg/model/workflow.go
  pkg/runner/expression_test.go
  pkg/runner/logger.go
  pkg/runner/res/trampoline.js
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: size/L

#608 Composite action
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
Labels: meta/needs-work, size/M

#635 Separate Container Workdir from host Workdir
  .gitignore
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/testdata/workdir/push.yml
Labels: size/L

#659 Mergify: configuration update
  .github/workflows/.gitignore
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/test-composite.yml
  .github/workflows/test-expressions.yml
  .github/workflows/test-if.yml
  .mergify.yml
  codecov.yml
Labels: size/XL

#661 Mergify: configuration update
  .mergify.yml
Labels: size/XS

#662 Mergify: configuration update
  .mergify.yml
Labels: size/XS

#663 Mergify: configuration update
  .mergify.yml
Labels: size/XS

#660 Remove pwsh -login and add Pwsh test
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/runner_test.go
Labels: size/S

#665 Add custom docker registry authentication
  pkg/container/docker_pull.go
  pkg/container/docker_pull_test.go
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
Labels: needs-work, size/M

#658 GitHub Enterprise support
  README.md
  cmd/input.go
  cmd/root.go
  pkg/common/git.go
  pkg/common/git_test.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
Labels: needs-work, size/M

#628 Fixes #598
  pkg/model/planner.go
  pkg/model/workflow.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/issue-598/spelling.yml
Labels: needs-work, size/M

#667 Fix environment variables and move `envs.txt`/`event.json` to fixed location
  pkg/container/docker_run.go
  pkg/model/workflow.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
Labels: size/M

#566 $GITHUB_PATH support
  .golangci.yml
  cmd/root.go
  pkg/container/docker_run.go
  pkg/model/planner.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/env-and-path/push.yaml
Labels: size/L, stale-exempt

#672 Add install instructions for `go`
  README.md
Labels: kind/feature-request, size/M

#670 Write git clone progress only if terminal is a TTY
  go.mod
  pkg/common/git.go
Labels: needs-work, size/M

#604 Add various GitHub environment variables
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
  pkg/runner/testdata/uses-composite/composite_action/action.yml
Labels: size/L

#674 Replace `gopass` lib with `golang.org/x/term`
  cmd/secrets.go
  go.mod
  go.sum
Labels: size/S

#675 fix: remove Windows issue from `README.md`
  README.md
Labels: needs-work, size/XS

#679 Refactor `git` to add more errors, tests and specific GitHub Actions error
  pkg/common/git.go
  pkg/common/git_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/testdata/uses-github-full-sha/main.yml
  pkg/runner/testdata/uses-github-short-sha/main.yml
Labels: size/L

#668 fix: hide masked value
  pkg/runner/command.go
  pkg/runner/command_test.go
Labels: size/S

#686 Add hint on ${{ github.token }}
  README.md
Labels: size/XS

#685 Fix typo
  README.md
Labels: size/XS

#688 refactor: remove `gotest.tools`
  .github/workflows/checks.yml
  .golangci.yml
  cmd/input.go
  go.mod
  pkg/container/docker_pull_test.go
  pkg/runner/expression_test.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
Labels: size/L

#687 fix: use auth when fetching (same as with cloning)
  pkg/common/git.go
Labels: size/S

#690 Fix: GITHUB_PATH should prepend
  pkg/container/docker_run.go
  pkg/runner/testdata/env-and-path/push.yaml
Labels: size/S

#693 fix: use github auth token for pulling a repository
  pkg/common/git.go
Labels: size/S

#691 Have List suggest -W for duplicate jobs
  cmd/list.go
Labels: size/S

#698 feat: add option for custom socket path
  README.md
  cmd/input.go
  cmd/root.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/M

#699 Add `arm64`/`arm` and capture all snapshots
  .github/workflows/checks.yml
  .goreleaser.yml
Labels: size/M

#701 Move actions path outside of workdir
  pkg/container/docker_run.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/step_context.go
Labels: size/M

#702 fix: avoid race condition by not running exec/start twice
  pkg/container/docker_run.go
Labels: size/XS
