Repository nektos/act, pull requests merged in 2022-09, with the labels that each got.

#1328 fix: show workflow name when get error on yml parsing (#1133)
  pkg/model/planner.go
Labels: size/XS

#1354 Improve hint for inserting secrets securely
  README.md
Labels: size/XS

#1355 Arch best practice is to not run partial upgrades
  README.md
Labels: size/XS

#1349 fix: missing defaults in nodejs pre
  pkg/runner/action.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/remote-action-composite-js-pre-with-defaults/push.yml
Labels: size/S

#1348 fix: crash on invalid docker credentials
  pkg/runner/job_executor.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/job-container-invalid-credentials/push.yml
Labels: size/S

#1362 fix: align github.ref to GitHub Action
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: kind/bug, size/M

#1364 feat: pass current matrix information to job logger
  pkg/runner/command_test.go
  pkg/runner/logger.go
  pkg/runner/runner.go
Labels: size/XS

#1365 fix: restore the job logger setup after job cancelation
  pkg/runner/job_executor.go
Labels: size/XS

#1335 fix: show workflow info even if on.push is not defined (#1329)
  README.md
  cmd/root.go
  pkg/model/planner.go
Labels: size/L
