Repository nektos/act, pull requests merged in 2022-10, with the labels that each got.

#1374 fix: handle go closure iteration
  pkg/runner/runner.go
Labels: kind/bug, size/XS

#1345 Fix composite input handling
  pkg/model/workflow.go
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/action_test.go
  pkg/runner/expression.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_docker.go
  pkg/runner/step_run.go
  pkg/runner/step_test.go
  pkg/runner/testdata/uses-composite-with-inputs/action/action.yml
  pkg/runner/testdata/uses-composite-with-inputs/composite/action.yml
  pkg/runner/testdata/uses-composite-with-inputs/push.yml
  pkg/runner/testdata/uses-composite/composite_action/action.yml
  pkg/runner/testdata/uses-nested-composite/composite_action2/action.yml
Labels: size/L

#1351 fix: support docker create arguments from container.options (#1022)
  .mega-linter.yml
  IMAGES.md
  README.md
  go.mod
  go.sum
  pkg/common/git/git.go
  pkg/container/DOCKER_LICENSE
  pkg/container/docker_cli.go
  pkg/container/docker_cli_test.go
  pkg/container/docker_run.go
  pkg/container/file_collector.go
  pkg/container/testdata/utf16.env
  pkg/container/testdata/utf16be.env
  pkg/container/testdata/utf8.env
  pkg/container/testdata/valid.env
  pkg/container/testdata/valid.label
  pkg/exprparser/interpreter.go
  pkg/model/planner.go
  pkg/runner/run_context.go
  pkg/runner/testdata/container-hostname/push.yml
Labels: size/XXL

#1376 fix: interpolate action input defaults
  pkg/runner/action_composite.go
  pkg/runner/testdata/uses-composite-with-inputs/action/action.yml
Labels: kind/bug, size/S

#1385 fix: re-evaluate env for remote composite actions
  pkg/runner/step_action_remote.go
  pkg/runner/testdata/uses-composite-with-inputs/push.yml
Labels: kind/bug, size/S

#1375 test: add test for networking setup in act
  pkg/container/docker_run.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/networking/push.yml
Labels: kind/bug, size/M

#1397 fix: ci is failing since 2022-10-17
  pkg/runner/testdata/issue-104/main.yaml
  pkg/runner/testdata/local-action-via-composite-dockerfile/action.yml
  pkg/runner/testdata/remote-action-docker/push.yml
Labels: size/XS

#1363 Mapping `workflow_dispatch` inputs into the Expression `inputs` context
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/workflow_dispatch/event.json
  pkg/runner/testdata/workflow_dispatch/workflow_dispatch.yml
Labels: size/L

#1388 Fixes #1387
  pkg/container/docker_run.go
  pkg/runner/testdata/env-and-path/push.yaml
Labels: size/S

#1416 Add user level Docker socket to common paths
  cmd/root.go
Labels: size/XS

#1417 refactor: move from io/ioutil to io and os packages
  pkg/common/file.go
  pkg/common/git/git.go
  pkg/common/git/git_test.go
  pkg/container/docker_images_test.go
  pkg/container/docker_run.go
  pkg/model/planner.go
  pkg/runner/runner.go
Labels: size/M
