Repository nektos/act, pull requests merged in 2022-06, with the labels that each got.

#1199 fix: dryrun skip local actions + enable Tests
  pkg/runner/runner_test.go
  pkg/runner/step_action_local.go
Labels: size/M

#1197 pkg/runner: add support to replace GitHub's env
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/issue-1195/push.yml
Labels: size/S

#1204 fix: skip local actions pre step in any case
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
Labels: kind/bug, size/L

#1077 refactor: remove github.com/pkg/errors dependency
  .golangci.yml
  go.mod
  pkg/common/git/git.go
  pkg/common/git/git_test.go
  pkg/container/docker_pull.go
  pkg/container/docker_run.go
  pkg/container/file_collector.go
  pkg/model/github_context.go
  pkg/model/planner.go
  pkg/model/planner_test.go
  pkg/runner/run_context.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
Labels: size/L

#1217 fix: allow TimeoutMinutes to be expression
  pkg/model/workflow.go
Labels: size/XS

#1171 Improve logging
  pkg/artifacts/server.go
  pkg/common/executor.go
  pkg/common/git/git.go
  pkg/common/git/git_test.go
  pkg/container/docker_auth.go
  pkg/container/docker_build.go
  pkg/container/docker_pull.go
  pkg/container/docker_pull_test.go
  pkg/container/docker_run.go
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/action_test.go
  pkg/runner/command.go
  pkg/runner/command_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/logger.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker.go
  pkg/runner/step_run.go
  pkg/runner/step_test.go
  pkg/runner/testdata/mask-values/composite/action.yml
  pkg/runner/testdata/mask-values/push.yml
Labels: size/XL

#1215 fix: keep action inputs
  pkg/runner/step_action_remote.go
Labels: kind/bug, size/L

#1208 Added support for chunked uploads.
  pkg/artifacts/server.go
  pkg/artifacts/server_test.go
  pkg/artifacts/testdata/upload-and-download/artifacts.yml
Labels: size/L

#1198 fix: localcheckout mock
  pkg/runner/run_context.go
  pkg/runner/step_action_remote.go
Labels: size/M

#1200 fix: processing of strategy.matrix.include
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/testdata/evalmatrix/push.yml
Labels: size/L

#1202 feat: non root user container
  pkg/container/docker_run.go
  pkg/container/file_collector.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
Labels: size/M

#1224 update runc and containerd
  go.mod
  go.sum
Labels: size/XS

#1225 auto generate changelog
  .github/workflows/release.yml
Labels: size/XS

#1162 feat: add option to bypass GHE for actions checkout
  README.md
  cmd/input.go
  cmd/root.go
  pkg/runner/runner.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
Labels: size/L
