Repository nektos/act, pull requests merged in 2022-05, with the labels that each got.

#1142 feat: support `GITHUB_REF_NAME` & `GITHUB_REF_TYPE`
  pkg/model/github_context.go
  pkg/runner/run_context.go
  pkg/runner/step_test.go
Labels: size/S

#1085 refactor: remove composite action runcontext workaround
  cmd/root.go
  pkg/container/docker_run.go
  pkg/runner/action.go
  pkg/runner/action_test.go
  pkg/runner/expression.go
  pkg/runner/logger.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/step_run.go
  pkg/runner/testdata/act-composite-env-test/action1/action.yml
  pkg/runner/testdata/act-composite-env-test/action2/action.yml
  pkg/runner/testdata/act-composite-env-test/push.yml
  pkg/runner/testdata/actions-environment-and-context-tests/docker/Dockerfile
  pkg/runner/testdata/actions-environment-and-context-tests/docker/action.yml
  pkg/runner/testdata/actions-environment-and-context-tests/docker/entrypoint.sh
  pkg/runner/testdata/actions-environment-and-context-tests/js/action.yml
  pkg/runner/testdata/actions-environment-and-context-tests/js/index.js
  pkg/runner/testdata/actions-environment-and-context-tests/push.yml
  pkg/runner/testdata/mask-values/composite/action.yml
  pkg/runner/testdata/mask-values/push.yml
Labels: stale-exempt, size/XL

#1141 fix: panic while running DRYRUN with local actions
  pkg/container/docker_run.go
Labels: size/XS

#1148 Remove the correct Volume
  pkg/runner/run_context.go
Labels: size/XS

#1157 fix: return invalid step type
  pkg/model/workflow.go
Labels: size/XS

#1145 fix: panic if a step in a job is nil
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/testdata/job-nil-step/push.yml
Labels: size/S

#1163 feat/bug-report-extended
  cmd/root.go
Labels: size/S

#1164 ci(choco): update chocolatey to 1.1.0
  .editorconfig
  .github/actions/choco/Dockerfile
  .mega-linter.yml
Labels: size/S

#1128 fix: remove composite restrictions
  pkg/model/workflow.go
  pkg/runner/action.go
  pkg/runner/runner.go
Labels: size/M

#1089 implement pre and post steps
  pkg/exprparser/functions_test.go
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
  pkg/model/action.go
  pkg/model/step_result.go
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/action_test.go
  pkg/runner/command.go
  pkg/runner/command_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/job_executor.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker.go
  pkg/runner/step_run.go
  pkg/runner/step_test.go
  pkg/runner/testdata/uses-action-with-pre-and-post-step/last-action/action.yml
  pkg/runner/testdata/uses-action-with-pre-and-post-step/last-action/main.js
  pkg/runner/testdata/uses-action-with-pre-and-post-step/last-action/post.js
  pkg/runner/testdata/uses-action-with-pre-and-post-step/push.yml
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/action-with-pre-and-post/action.yml
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/action-with-pre-and-post/main.js
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/action-with-pre-and-post/post.js
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/action-with-pre-and-post/pre.js
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/composite_action/action.yml
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/last-action/action.yml
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/last-action/main.js
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/last-action/post.js
  pkg/runner/testdata/uses-composite-with-pre-and-post-steps/push.yml
Labels: size/XXL

#1170 feat: handle context cancelation during docker exec
  main.go
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/runner/job_executor.go
  pkg/runner/runner.go
Labels: size/L

#1180 Update docs to reflect status of support for services
  README.md
Labels: size/XS

#1186 governance: fix bug report rendering
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size/XS
