Repository nektos/act, pull requests merged in 2022-12, with the labels that each got.

#1476 Pass `LANG=C.UTF-8` to environment
  pkg/runner/run_context.go
Labels: size/XS

#1480 docs: clarifying skipping steps / jobs
  README.md
Labels: size/M

#1463 refactor: move autoremove into the jobexecutor
  pkg/runner/job_executor.go
  pkg/runner/runner.go
Labels: size/M

#1462 feat: `--container-options`
  cmd/input.go
  cmd/root.go
  pkg/container/docker_run.go
  pkg/runner/action.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/S

#1458 fix: step env is unavailable in with property expr
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/testdata/inputs-via-env-context/action.yml
  pkg/runner/testdata/inputs-via-env-context/push.yml
Labels: size/M

#1493 fix: handle env-vars case sensitive
  pkg/model/workflow.go
  pkg/runner/step.go
  pkg/runner/testdata/environment-variables/push.yml
Labels: size/M

#1496 feat: JobLoggerFactory
  pkg/runner/logger.go
  pkg/runner/runner_test.go
Labels: size/M

#1472 refactor: fix add-path / GITHUB_PATH commands
  pkg/runner/action.go
  pkg/runner/command.go
  pkg/runner/command_test.go
  pkg/runner/container_mock_test.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker_test.go
  pkg/runner/step_run.go
  pkg/runner/step_run_test.go
  pkg/runner/step_test.go
Labels: size/L

#1423 feat: allow to spawn and run a local reusable workflow
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/reusable_workflow.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/.github/workflows/local-reusable-workflow.yml
  pkg/runner/testdata/uses-workflow/local-workflow.yml
Labels: size/XL

#1506 fix: tail (not absolute) as entrypoint of job container
  pkg/runner/run_context.go
Labels: size/XS

#1497 feat: Support "result" on "needs" context.
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/job-needs-context-contains-result/push.yml
Labels: size/M

#1510 fix: align runner.os / runner.arch to known values
  pkg/container/host_environment.go
  pkg/runner/run_context.go
Labels: size/M

#1514 revert: deprecation of containerArchitecture
  .github/actions/choco/Dockerfile
  cmd/root.go
Labels: size/XS
