Repository nektos/act, pull requests merged in 2022-07, with the labels that each got.

#1238 Improve docs for events inputs
  README.md
Labels: size/M

#1243 Improve --eventpath example command
  README.md
Labels: size/XS

#1249 fix: use docker images from dockerhub
  IMAGES.md
  README.md
  cmd/root.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/job-container-non-root/push.yml
  pkg/runner/testdata/shells/custom/push.yml
  pkg/runner/testdata/shells/pwsh/push.yml
Labels: size/M

#1247 fix: allow TimeoutMinutes to be expression in Jobs
  pkg/model/workflow.go
Labels: size/XS

#1250 only perform chown operation for non root users
  pkg/container/docker_run.go
Labels: size/XS

#1252 fix: the number in the github event is of type number
  pkg/model/github_context.go
  pkg/model/github_context_test.go
Labels: kind/bug, size/XS

#1260 Update README.md
  README.md
Labels: size/XS

#1222 Made env interpolated instead of evaluated.
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/evalenv/push.yml
Labels: size/S

#1268 fix: add parent step id in composite action step id
  pkg/runner/action_composite.go
  pkg/runner/logger.go
Labels: size/M

#1282 walk submodule path instead of dir name
  pkg/container/file_collector.go
Labels: size/XS

#1286 fix: ensure all post steps are executed
  pkg/runner/action_composite.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/ensure-post-steps/action-composite/action.yml
  pkg/runner/testdata/ensure-post-steps/action-post/action.yml
  pkg/runner/testdata/ensure-post-steps/action-post/main.js
  pkg/runner/testdata/ensure-post-steps/action-post/post.js
  pkg/runner/testdata/ensure-post-steps/push.yml
Labels: kind/bug, size/M
