Repository nektos/act, pull requests merged in 2022-03, with the labels that each got.

#1011 fix: hide masked values in log files
  pkg/runner/command.go
  pkg/runner/command_test.go
  pkg/runner/logger.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: size/M

#1024 fix: trim whitespace from actrc
  cmd/root.go
Labels: size/XS

#1030 fix: coerce booleans to numbers for comparison in exprparser
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
Labels: size/XS

#1049 feat: add flag to always run the checkout action
  cmd/input.go
  cmd/root.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/step_context.go
Labels: size/S

#1068 Fix: tojson(null) == 'null'
  pkg/exprparser/functions.go
  pkg/exprparser/functions_test.go
Labels: size/XS

#1067 Fix: call of reflect.Value.Interface on zero Value
  pkg/exprparser/interpreter.go
Labels: size/XS

#1066 Fix: panic: reflect: slice index out of range
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
Labels: size/XS

#1056 feat: add bug-report flag
  cmd/root.go
  pkg/container/docker_run.go
  pkg/runner/runner.go
Labels: size/L

#1004 feat: split job steps into its own files/structs
  pkg/runner/action.go
  pkg/runner/action_test.go
  pkg/runner/container_mock_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_context.go
  pkg/runner/step_context_test.go
  pkg/runner/step_docker.go
  pkg/runner/step_docker_test.go
  pkg/runner/step_factory.go
  pkg/runner/step_factory_test.go
  pkg/runner/step_run.go
  pkg/runner/step_run_test.go
  pkg/runner/step_test.go
Labels: size/XXL

#1057 deps: bump go-git
  go.mod
  go.sum
Labels: size/XS

#1084 automatically merge PRs from dependabot
  .mergify.yml
Labels: size/XS

#1070 fix: set default version string
  main.go
Labels: size/XS

#1086 deps: remove shlex
  go.mod
  go.sum
  pkg/runner/run_context.go
Labels: size/XS

#1083 refactor: simplify action function signatures
  pkg/runner/action.go
  pkg/runner/action_test.go
  pkg/runner/run_context.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
Labels: size/L

#1076 fix: don't overwrite with empty cmd/entrypoint
  pkg/container/docker_run.go
  pkg/runner/step_docker.go
  pkg/runner/testdata/uses-docker-url/push.yml
Labels: size/S

#1094 fix(editorconfig): correct braces
  .editorconfig
Labels: size/XS

#1088 deps: bump go.mod to go1.18
  README.md
  go.mod
  go.sum
Labels: size/XS

#1093 fix: return error on reusable workflows
  pkg/model/workflow.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/uses-workflow/push.yml
Labels: size/S
