Repository nektos/act, pull requests merged in 2022-01, with the labels that each got.

#942 feat(goreleaser): format changelog, add prereleases
  .goreleaser.yml
Labels: size/S

#962 fix(goreleaser): add append mode for release notes
  .goreleaser.yml
Labels: size/XS

#908 Refactor expression evaluator to use parser from actionlint package
  go.mod
  go.sum
  pkg/exprparser/functions.go
  pkg/exprparser/functions_test.go
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
  pkg/exprparser/testdata/for-hashing-1.txt
  pkg/exprparser/testdata/for-hashing-2.txt
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: size/XXL

#945 fix: set composite outputs on failure
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/step_context.go
  pkg/runner/testdata/actions/composite-fail-with-output/action.yml
  pkg/runner/testdata/composite-fail-with-output/push.yml
Labels: size/M

#889 feat: try to read ref and sha from event payload if available
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/runner/run_context.go
Labels: size/L

#950 feat: add skipped status as step result
  pkg/model/step_result.go
  pkg/runner/run_context.go
Labels: size/XS

#965 Test: env.ACT in if condition of the workflow
  pkg/runner/runner_test.go
  pkg/runner/testdata/if-env-act/push.yml
Labels: size/S

#966 ci(Mergify): configuration update
  .mergify.yml
Labels: size/XS

#948 fix: docker cp of dangling symlink (#943)
  pkg/container/docker_run.go
Labels: size/XS

#972 ci(Mergify): configuration update
  .mergify.yml
Labels: size/S

#968 docs: Expand the GITHUB_TOKEN section
  README.md
Labels: size/S
