Repository nektos/act, pull requests merged in 2022-04, with the labels that each got.

#1074 fix: copy ignored tracked files
  pkg/container/docker_run.go
  pkg/container/file_collector.go
  pkg/container/file_collector_test.go
Labels: size/L

#1100 Allow passed in env vars to supersede ones declared in the workflow
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: size/M

#1104 feat: add option to specify git remote name
  cmd/input.go
  cmd/root.go
  pkg/common/git.go
  pkg/common/git_test.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/S

#1101 implement volume mount for container job
  pkg/model/testdata/container-volumes/push.yml
  pkg/model/workflow_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
Labels: size/M

#1095 tests(runner): move arm64 test to own func
  pkg/runner/job_executor_test.go
  pkg/runner/run_context_test.go
  pkg/runner/runner_test.go
Labels: size/L

#1129 README: add MacPorts badge
  README.md
Labels: size/XS

#1135 use new paths from goreleaser
  .editorconfig
  .github/actions/choco/entrypoint.sh
  .github/workflows/checks.yml
Labels: size/S

#1127 tests: remove runTestJobFile
  pkg/runner/job_executor_test.go
  pkg/runner/runner_test.go
Labels: size/S

#1124 ci: always grab latest go version
  .github/workflows/checks.yml
  .github/workflows/release.yml
Labels: size/XS

#1123 docs(README): remove go install
  README.md
Labels: size/S

#1111 chore: fold integration test outputs
  pkg/artifacts/server_test.go
  pkg/runner/job_executor_test.go
  pkg/runner/runner_test.go
Labels: size/S

#1136 fix: conclusion and outcome are no integers
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
  pkg/runner/expression_test.go
Labels: size/M
