Repository nektos/act, pull requests merged in 2022-02, with the labels that each got.

#984 refactor: extract RunContext Executor in JobExecutor
  go.sum
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/run_context.go
Labels: size/L

#986 refactor: extract setupAction into ActionReader
  pkg/runner/action.go
  pkg/runner/action_test.go
  pkg/runner/step_context.go
Labels: size/L

#993 Added instructions to install on fedora using copr package
  README.md
Labels: size/XS

#964 fix: deep evaluate matrix strategy
  pkg/runner/expression.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/evalmatrix-merge-array/push.yml
  pkg/runner/testdata/evalmatrix-merge-map/push.yml
  pkg/runner/testdata/evalmatrix/push.yml
  pkg/runner/testdata/evalmatrixneeds/push.yml
  pkg/runner/testdata/evalmatrixneeds2/push.yml
Labels: size/L

#990 refactor: default empty if: statement to if: success() in evaluator & remove `FixIfStatement()`
  pkg/exprparser/interpreter.go
  pkg/model/action.go
  pkg/model/planner.go
Labels: size/M

#1014 fix: print line after password prompt
  cmd/secrets.go
Labels: size/XS

#1009 Expression evaluator fixes
  pkg/common/executor.go
  pkg/exprparser/interpreter.go
  pkg/runner/expression.go
  pkg/runner/run_context.go
  pkg/runner/step_context.go
  pkg/runner/testdata/issue-597/spelling.yaml
  pkg/runner/testdata/uses-composite/push.yml
Labels: size/L

#1003 feat: run jobs in parallel
  pkg/common/executor.go
  pkg/common/executor_test.go
  pkg/runner/runner.go
Labels: size/M

#1016 fix: Update link to 'filesystems' GitHub docs
  README.md
Labels: size/XS
