Repository nektos/act, pull requests merged in 2022-11, with the labels that each got.

#1414 feat: parse types of reusable workflows
  pkg/model/workflow.go
  pkg/model/workflow_test.go
Labels: size/M

#1432 fix: nil pointer access ( workflow_dispatch )
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/workflow_dispatch-scalar-composite-action/workflow_dispatch.yml
  pkg/runner/testdata/workflow_dispatch-scalar/workflow_dispatch.yml
  pkg/runner/testdata/workflow_dispatch_no_inputs_mapping/workflow_dispatch.yml
Labels: size/M

#1428 fix: keep path to event json file in composite actions
  pkg/runner/action_composite.go
  pkg/runner/testdata/pull-request/main.yaml
Labels: kind/bug, size/S

#1293 feat: Host environment
  .github/workflows/checks.yml
  go.mod
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/container/executions_environment.go
  pkg/container/file_collector.go
  pkg/container/host_environment.go
  pkg/container/host_environment_test.go
  pkg/container/linux_container_environment_extensions.go
  pkg/container/linux_container_environment_extensions_test.go
  pkg/container/util.go
  pkg/container/util_openbsd_mips64.go
  pkg/container/util_plan9.go
  pkg/container/util_windows.go
  pkg/lookpath/LICENSE
  pkg/lookpath/env.go
  pkg/lookpath/error.go
  pkg/lookpath/lp_js.go
  pkg/lookpath/lp_plan9.go
  pkg/lookpath/lp_unix.go
  pkg/lookpath/lp_windows.go
  pkg/runner/action.go
  pkg/runner/container_mock_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_docker.go
  pkg/runner/step_docker_test.go
  pkg/runner/step_run.go
  pkg/runner/testdata/nix-prepend-path/push.yml
  pkg/runner/testdata/windows-add-env/push.yml
  pkg/runner/testdata/windows-prepend-path/push.yml
Labels: size/XXL

#1391 feat: GITHUB_STATE and GITHUB_OUTPUT file commands
  .github/workflows/checks.yml
  pkg/runner/step.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker_test.go
  pkg/runner/step_run_test.go
Labels: size/L

#1422 feat: interpolate the step names
  pkg/runner/action_composite.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/step.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker_test.go
Labels: size/S

#1425 Remove dead code
  pkg/container/docker_logger.go
Labels: size/M

#1446 fix: handle subdirectories and exclusions (#1012)
  pkg/exprparser/functions.go
  pkg/exprparser/functions_test.go
  pkg/exprparser/testdata/for-hashing-3/data.txt
  pkg/exprparser/testdata/for-hashing-3/nested/nested-data.txt
Labels: size/M

#1456 fix readme typo
  README.md
Labels: size/XS

#1464 Fix shellcommand error on alpine sh shell
  pkg/model/workflow.go
Labels: size/XS

#1471 act -j -W example
  README.md
Labels: size/XS
