Repository nektos/act, pull requests merged in 2023-05, with the labels that each got.

#1784 fix: remove hardcoded reference to github.com when using reusable remote workflows and remote actions
  pkg/runner/reusable_workflow.go
  pkg/runner/step_action_remote.go
Labels: size/M

#1774 fix: fallback to unauthenticated pull
  pkg/container/docker_pull.go
Labels: size/S

#1761 Refactor evaluate yaml node do not alter nested nodes
  pkg/runner/expression.go
Labels: size/L

#1783 fix: don't allow `-self-hosted` mode as container image
  pkg/runner/run_context.go
Labels: size/S

#1776 feat: implement steps.timeout-minutes
  pkg/runner/step.go
Labels: size/S

#1831 add instruction for using `gh auth token`
  README.md
Labels: size/XS
