Repository nektos/act, pull requests merged in 2023-11, with the labels that each got.

#2071 Fix panic in `extractFromImageEnv`
  pkg/container/docker_run.go
Labels: kind/bug, size/S

#2015 Use unique name for reusable workflows
  pkg/runner/run_context.go
Labels: size/XS

#2088 Support array expressions in runs-on
  cmd/platforms.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: size/M

#2089 Don't set `GITHUB_TOKEN` env variable
  pkg/runner/run_context.go
  pkg/runner/step_test.go
Labels: size/XS

#2075 fix: network-scoped alias is supported only for containers in user defined networks
  pkg/container/docker_run.go
Labels: size/XS

#2054 Interpolate all service values
  pkg/runner/run_context.go
Labels: size/S

#2062 feat: support runs-on labels and group
  pkg/model/workflow.go
  pkg/model/workflow_test.go
Labels: size/M

#2087 Evaluate if condition when calling a reusable workflow
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: size/S
