Repository nektos/act, pull requests merged in 2023-07, with the labels that each got.

#1879 refactor: open boltdb only while using it
  pkg/artifactcache/handler.go
  pkg/artifactcache/handler_test.go
Labels: size/L

#1895 Remove `archives.replacements` in `goreleaser.yaml`
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
Labels: size/S

#1898 Normalize path outputs emitted by the artifact server download endpoint
  pkg/artifacts/server.go
Labels: needs-work, size/XS

#1904 chore: upgrade golangci-lint and address findings
  .github/workflows/checks.yml
  .golangci.yml
  cmd/root.go
  pkg/artifacts/server.go
  pkg/common/git/git.go
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/container/host_environment.go
  pkg/container/util.go
  pkg/exprparser/interpreter.go
  pkg/runner/action.go
  pkg/runner/command.go
  pkg/runner/expression.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker.go
  pkg/runner/step_run.go
Labels: size/L

#1888 Handle cache requests without a size that are sent by old versions of actions
  pkg/artifactcache/handler.go
  pkg/artifactcache/model.go
  pkg/artifactcache/storage.go
Labels: size/M

#1804 throw when invalid `uses` key is provided
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/L

#1905 Bump dockercli
  .github/workflows/checks.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  README.md
  go.mod
  go.sum
  pkg/container/docker_auth.go
  pkg/container/docker_pull.go
  pkg/container/docker_volume.go
Labels: needs-work, size/M

#1920 Add new CLI flag to log just the job id and not the entire job name
  .github/actions/run-tests/action.yml
  cmd/input.go
  cmd/root.go
  pkg/runner/logger.go
  pkg/runner/runner.go
Labels: size/M

#1911 local runner doc
  README.md
Labels: size/XS
