Repository nektos/act, pull requests merged in 2023-06, with the labels that each got.

#1834 Fix bug in processing jobs on platforms without Docker
  pkg/common/executor.go
  pkg/common/executor_test.go
  pkg/model/workflow.go
  pkg/runner/runner.go
Labels: size/M

#1833 feature: Add support for github action variables
  cmd/input.go
  cmd/root.go
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/runner.go
Labels: size/M

#1854 fix: spelling mistake in readme
  README.md
Labels: size/XS

#1864 Drop disappeared `wei/curl@v1`
  pkg/artifacts/server_test.go
  pkg/artifacts/testdata/GHSL-2023-004/artifacts.yml
Labels: size/S

#1863 Allow to override location of action cache dir
  cmd/input.go
  cmd/root.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/XS

#1845 Allow inputs for workflow_calls
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/workflow_call_inputs/event.json
  pkg/runner/testdata/workflow_call_inputs/workflow_call_inputs.yml
Labels: size/M
