Repository nektos/act, pull requests merged in 2023-01, with the labels that each got.

#1519 fix: preserve job result state in case of failure
  pkg/runner/job_executor.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/matrix-exitcode/push.yml
Labels: size/M

#1520 test: make sure workflow_call is not a github event calling our workflow
  pkg/runner/testdata/.github/workflows/local-reusable-workflow.yml
Labels: size/XS

#1531 fix: extra path lost in composite actions
  pkg/runner/runner_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/testdata/path-handling/action.yml
  pkg/runner/testdata/path-handling/push.yml
Labels: size/M

#1507 feat: Allow building without docker support
  pkg/container/container_types.go
  pkg/container/docker_auth.go
  pkg/container/docker_build.go
  pkg/container/docker_cli.go
  pkg/container/docker_images.go
  pkg/container/docker_logger.go
  pkg/container/docker_pull.go
  pkg/container/docker_run.go
  pkg/container/docker_stub.go
  pkg/container/docker_volume.go
Labels: size/L

#1557 feat: add support for building docker actions with private registries
  pkg/container/docker_auth.go
  pkg/container/docker_build.go
Labels: size/S

#1532 fix: add-matcher fails github workflow
  pkg/runner/command.go
  pkg/runner/testdata/uses-nested-composite/composite_action2/action.yml
Labels: size/M

#1501 refactor: remove docker image list reference filter
  pkg/container/docker_images.go
Labels: size/M

#1524 Input
  README.md
  cmd/input.go
  cmd/root.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/input-from-cli/input.yml
Labels: size/L

#1562 feat: add check for newer versions
  .mega-linter.yml
  Makefile
  VERSION
  cmd/notices.go
  cmd/root.go
  main.go
Labels: size/L

#1560 fix: allow override of artifact server bind address
  README.md
  cmd/input.go
  cmd/root.go
  pkg/artifacts/server.go
  pkg/artifacts/server_test.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/M

#1530 Feature/allow worktrees
  pkg/common/git/git.go
  pkg/common/git/git_test.go
Labels: size/L

#1566 Fixed auto-generated platform configuration with Micro size image
  cmd/root.go
Labels: size/XS

#1525 feat: add remote reusable workflows
  pkg/runner/reusable_workflow.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/uses-workflow/push.yml
Labels: size/L

#1569 refactor: pull and rebuild docker images by default
  cmd/root.go
Labels: size/XS

#1580 feat: step summary of test results
  .github/actions/run-tests/action.yml
  .github/workflows/checks.yml
Labels: size/M

#1585 test: Do not leak step env in composite
  pkg/runner/runner_test.go
  pkg/runner/testdata/do-not-leak-step-env-in-composite/push.yml
Labels: size/S

#1587 ci: make stalebot less annoying
  .github/workflows/stale.yml
Labels: size/XS
