Repository nektos/act, pull requests merged in 2023-08, with the labels that each got.

#1939 fix: Shorten or/and in expressions
  pkg/exprparser/interpreter.go
Labels: size/S

#1914 refactor: docker build BuildContext field
  pkg/container/container_types.go
  pkg/container/docker_build.go
  pkg/runner/action.go
Labels: size/M

#1941 fix: cmd support for windows
  pkg/container/host_environment.go
  pkg/model/workflow.go
  pkg/runner/runner_test.go
  pkg/runner/step_run.go
  pkg/runner/testdata/windows-shell-cmd/push.yml
Labels: size/S

#1913 feat: Add new Action Cache
  pkg/runner/action_cache.go
  pkg/runner/action_cache_test.go
Labels: size/L

#1955 refactor: remove unnecessary nil check in RunContext
  pkg/runner/run_context.go
Labels: size/S

#1957 Fix "Unknown server OS" for Docker container `--device` option
  pkg/container/docker_run.go
Labels: size/XS

#1961 change podman socket path
  cmd/root.go
Labels: size/XS

#1959 ci: change winget job runner to `ubuntu-latest`
  .github/workflows/release.yml
Labels: size/S

#1973 Mention act user guide in act
  CONTRIBUTING.md
  README.md
Labels: size/XS
