Repository nektos/act, pull requests merged in 2023-02, with the labels that each got.

#1592 feat: cache notices to reduce frequency of upgrade notifications
  cmd/notices.go
Labels: size/M

#1599 fix: Apply forcePull only for prebuild docker actions
  pkg/runner/action.go
Labels: size/XS

#1596 Docker build fixes
  pkg/runner/action.go
Labels: size/XS

#1582 feat: allow overriding of `GITHUB_` env variables
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/runner/run_context.go
Labels: size/L

#1597 Update max container name length
  pkg/runner/run_context.go
Labels: size/S

#1606 Pass dockerfile to build executor
  pkg/container/container_types.go
  pkg/container/docker_build.go
  pkg/runner/action.go
  pkg/runner/testdata/actions-environment-and-context-tests/push.yml
Labels: size/XS

#1622 chore: add Winget installation instructions
  README.md
Labels: size/XS

#1623 ci: add Winget Releaser workflow
  .github/workflows/release.yml
Labels: size/XS

#1629 fix: don't use os.Environ to override env
  pkg/runner/run_context.go
Labels: size/XS

#1630 chore: use new form of octal
  cmd/notices.go
  pkg/artifacts/server.go
  pkg/common/git/git.go
  pkg/common/git/git_test.go
  pkg/container/file_collector.go
  pkg/container/file_collector_test.go
  pkg/container/host_environment.go
  pkg/runner/action.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_run.go
  pkg/runner/step_run_test.go
Labels: size/M

#1631 chore: Remove obsolete Container.UpdateFromPath
  pkg/container/container_types.go
  pkg/container/docker_run.go
  pkg/container/host_environment.go
  pkg/runner/container_mock_test.go
Labels: size/M

#1619 fix: tolerate workflow that needs a missing job (#1595)
  cmd/root.go
  pkg/artifacts/server_test.go
  pkg/model/planner.go
  pkg/model/workflow_test.go
  pkg/runner/reusable_workflow.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/issue-1595/missing.yml
  pkg/runner/testdata/issue-1595/no-event.yml
  pkg/runner/testdata/issue-1595/no-first.yml
Labels: size/L

#1607 fix: add GITHUB_STEP_SUMMARY
  pkg/runner/step.go
Labels: size/S

#1618 feat: workflowpattern package
  pkg/workflowpattern/trace_writer.go
  pkg/workflowpattern/workflow_pattern.go
  pkg/workflowpattern/workflow_pattern_test.go
Labels: size/XL

#1648 docs: remove help section
  README.md
Labels: size/M

#1616 fix: crash malformed composite action
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/no-panic-on-invalid-composite-action/push.yml
Labels: size/M

#1521 fix: update output handling for reusable workflows
  pkg/exprparser/interpreter.go
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/job_executor.go
  pkg/runner/testdata/.github/workflows/local-reusable-workflow.yml
Labels: size/M

#1646 fix: github.job property is empty, GITHUB_JOB should be job id
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/step_test.go
Labels: size/XS
