Repository nektos/act, pull requests merged in 2023-03, with the labels that each got.

#1645 fix: compare properties of Invalid types
  pkg/exprparser/interpreter.go
  pkg/exprparser/interpreter_test.go
Labels: size/S

#1651 fix: make sure using a safe name to store actions on unix-like and windows
  pkg/runner/action.go
  pkg/runner/reusable_workflow.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
Labels: size/M

#1656 Improve XDG Spec supporting
  cmd/root.go
  go.mod
  go.sum
Labels: size/S

#1660 fix: crash if the id tool fails to run in the container
  pkg/container/docker_run.go
  pkg/runner/testdata/remote-action-js-node-user/push.yml
Labels: size/S

#1661 test: Enshure ForcePull config doesn't break docker actions
  pkg/runner/runner_test.go
Labels: size/S

#1667 fix: return error instead of panic when walking in a nonexistent dir
  pkg/exprparser/functions.go
Labels: size/XS

#1672 fix: correct ref and ref_name
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/runner/run_context_test.go
Labels: kind/bug, size/S

#1674 Support for docker steps in host environment
  pkg/runner/action.go
  pkg/runner/run_context.go
Labels: size/S

#1675 feat: specify matrix on command line
  cmd/input.go
  cmd/root.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/matrix-with-user-inclusions/push.yml
Labels: size/L

#1671 Add example command for collecting artifacts
  README.md
Labels: size/XS

#1670 full path required for extension install
  README.md
Labels: size/XS

#1707 Improve GetOutboundIP to work without internet access
  pkg/common/outbound_ip.go
Labels: size/M
