Repository nektos/act, pull requests merged in 2023-04, with the labels that each got.

#1725 build(deps): update go-git to ce62f3e9ff86270538a514a68d3bd5563a733e3b
  go.mod
  go.sum
Labels: size/L

#1727 fix: add `server_url` attribute to github context
  pkg/model/github_context.go
  pkg/runner/run_context.go
Labels: size/M

#1728 fix: reusable workflow panic
  pkg/model/workflow.go
  pkg/runner/testdata/.github/workflows/local-reusable-workflow-no-inputs-array.yml
  pkg/runner/testdata/.github/workflows/local-reusable-workflow-no-inputs-string.yml
  pkg/runner/testdata/uses-workflow/local-workflow.yml
Labels: size/S

#1705 Avoid using `log.Fatal` in `pkg/*`
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
Labels: size/M

#1732 fix: environment handling windows (host mode)
  pkg/container/executions_environment.go
  pkg/container/host_environment.go
  pkg/container/linux_container_environment_extensions.go
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/command.go
  pkg/runner/run_context.go
  pkg/runner/step.go
  pkg/runner/step_test.go
  pkg/runner/testdata/windows-add-env/action.yml
  pkg/runner/testdata/windows-add-env/push.yml
  pkg/runner/testdata/windows-prepend-path/push.yml
Labels: size/L

#1691 Remove the comment-out code
  pkg/runner/runner_test.go
  pkg/runner/testdata/issue-228/main.yaml
Labels: size/S

#1743 Improve watchAndRun
  cmd/root.go
Labels: area/cli, size/M

#1745 fix: try finding a socket, otherwise fail, respect user choice
  cmd/root.go
  pkg/container/docker_run.go
Labels: size/M

#1751 ci: deduplicate running workflows
  .github/workflows/checks.yml
Labels: size/XS

#1759 Avoid using `log.Fatal` in `pkg/*`
  pkg/model/workflow.go
Labels: size/M

#1758 chore: run act from cli on linux
  .github/workflows/checks.yml
Labels: size/XS

#1770 Support cache
  cmd/dir.go
  cmd/input.go
  cmd/notices.go
  cmd/root.go
  go.mod
  go.sum
  pkg/artifactcache/doc.go
  pkg/artifactcache/handler.go
  pkg/artifactcache/handler_test.go
  pkg/artifactcache/model.go
  pkg/artifactcache/storage.go
  pkg/artifactcache/testdata/example/example.yaml
Labels: size/XXL
