Repository nektos/act, pull requests merged in 2023-10, with the labels that each got.

#2032 [ Variables ] - Add missing documentation for repository variables
  README.md
Labels: size/XS

#2022 fix: image survey for large images
  cmd/root.go
Labels: size/XS

#1940 fix: use actions/runner hashfiles in container
  pkg/exprparser/interpreter.go
  pkg/runner/expression.go
  pkg/runner/hashfiles/index.js
Labels: size/XXL

#2020 fix github.action_ref / github.job (composite action)
  pkg/runner/action_composite.go
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/remote-action-composite-action-ref/push.yml
Labels: size/S

#2018 Fix float formatting
  pkg/exprparser/functions_test.go
  pkg/exprparser/interpreter.go
Labels: size/XS

#1949 Add support for service containers
  cmd/input.go
  cmd/root.go
  pkg/container/container_types.go
  pkg/container/docker_network.go
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/container/docker_stub.go
  pkg/runner/job_executor.go
  pkg/runner/run_context.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/services-host-network/push.yml
  pkg/runner/testdata/services-with-container/push.yml
  pkg/runner/testdata/services/push.yaml
Labels: size/XL
