Repository nektos/act, pull requests merged in 2024-09, with the labels that each got.

#2402 fix: artifact v4 upload above 8MB
  pkg/artifacts/arifacts_v4.go
Labels: size/S

#2446 fix: schema validation for job if functions
  pkg/schema/schema.go
  pkg/schema/schema_test.go
Labels: size/L

#2352 feat: generate manual page automatically with cobra/doc
  cmd/root.go
  go.mod
  go.sum
Labels: size/S

#2449 Manage special bash options when no shell is defined in a workflow
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/run_context_test.go
  pkg/runner/step_run.go
Labels: size/M

#2454 Fix install sh usage
  install.sh
Labels: size/XS

#2458 run_context: add GITHUB_RUN_ATTEMPT
  pkg/model/github_context.go
  pkg/runner/run_context.go
  pkg/runner/step_test.go
Labels: size/XS
