Repository nektos/act, pull requests merged in 2024-01, with the labels that each got.

#2023 Add support for NetBSD
  pkg/container/docker_auth.go
  pkg/container/docker_build.go
  pkg/container/docker_cli.go
  pkg/container/docker_images.go
  pkg/container/docker_logger.go
  pkg/container/docker_network.go
  pkg/container/docker_pull.go
  pkg/container/docker_run.go
  pkg/container/docker_stub.go
  pkg/container/docker_volume.go
Labels: size/S

#2156 CI: change automatic merge rules for maintainers
  .mergify.yml
Labels: size/XS

#1954 feat: cli option to enable the new action cache
  cmd/input.go
  cmd/root.go
  pkg/container/docker_run.go
  pkg/model/planner.go
  pkg/runner/action.go
  pkg/runner/reusable_workflow.go
  pkg/runner/runner.go
  pkg/runner/step.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_remote.go
Labels: size/L

#2128 feat: support offline mode
  cmd/input.go
  cmd/root.go
  pkg/common/git/git.go
  pkg/runner/reusable_workflow.go
  pkg/runner/runner.go
  pkg/runner/step_action_remote.go
Labels: size/M

#2153 fix: match cache `restore-keys` in creation reverse order
  pkg/artifactcache/handler.go
Labels: size/XS

#2123 WorkflowDispatchConfig supports multiple yaml node kinds
  pkg/model/workflow.go
  pkg/model/workflow_test.go
Labels: size/L

#2140 fix: write default config in XDG config dir to avoid cluttering the HOME directory by default
  cmd/root.go
Labels: size/XS

#2168 Add containerd's normalized architectures to archMapper
  pkg/container/docker_run.go
Labels: size/XS

#2162 refactor(cmd/root): simplify `parseEnvs`
  cmd/root.go
Labels: size/S

#2171 fix: improve action not found error
  pkg/runner/action.go
Labels: size/S

#2170 fix: subpath actions via new artifact cache
  pkg/runner/action.go
  pkg/runner/step_action_remote.go
Labels: size/S

#2172 fix: improve new-action-cache fetch failure error
  pkg/runner/action_cache.go
  pkg/runner/step_action_remote.go
Labels: size/S

#2169 fix: improve warning about remote not found
  pkg/model/github_context.go
Labels: size/XS

#2174 refactor: filecollector into new package
  pkg/container/docker_run.go
  pkg/container/host_environment.go
  pkg/container/host_environment_test.go
  pkg/container/testdata/scratch/test.txt
  pkg/filecollector/file_collector.go
  pkg/filecollector/file_collector_test.go
Labels: size/L

#1494 fix: use correct path to toolcache
  pkg/runner/run_context.go
Labels: size/XS
