Repository nektos/act, pull requests merged in 2024-05, with the labels that each got.

#2272 Fix for issue 2232: Many lines of "Could not find any stages to run" on run
  cmd/root.go
  pkg/model/planner.go
  pkg/model/planner_test.go
Labels: size/S

#2311 Add documentation for `dryrun` parameter
  cmd/root.go
Labels: size/XS

#2224 Actions Artifacts v4 backend
  codecov.yml
  go.mod
  go.sum
  pkg/artifacts/arifacts_v4.go
  pkg/artifacts/artifact.pb.go
  pkg/artifacts/server.go
  pkg/artifacts/server_test.go
  pkg/artifacts/testdata/v4/artifacts.yml
  pkg/common/auth.go
  pkg/common/auth_test.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
Labels: size/XL

#2337 Meta-copy-symlinks-new-actions-cache
  pkg/filecollector/file_collector.go
  pkg/runner/action_cache.go
Labels: size/L
