Repository nektos/act, pull requests merged in 2024-03, with the labels that each got.

#2236 fix: docker buildx cache restore not working
  pkg/artifactcache/handler.go
Labels: size/XS

#2242 fix: rootless permission bits (new actions cache)
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
Labels: size/M

#2266 Use ping to improve network test
  pkg/runner/testdata/networking/push.yml
Labels: kind/bug, size/XS

#2265 Support overwriting caches
  pkg/artifactcache/handler.go
  pkg/artifactcache/handler_test.go
  pkg/artifactcache/model.go
Labels: kind/bug, size/L

#2259 chore: remove repetitive words
  IMAGES.md
  pkg/runner/action_composite.go
Labels: size/XS

#2256 Trivial: reduce log spam.
  pkg/common/executor.go
Labels: size/XS

#2267 fix: cache adjust restore order of exact key matches
  pkg/artifactcache/handler.go
  pkg/artifactcache/handler_test.go
Labels: size/L
