Repository nektos/act, pull requests merged in 2024-12, with the labels that each got.

#2580 fix: amd64 arch to X64
  pkg/container/host_environment.go
Labels: needs-work, size/XS

#2589 chore: upgrade dependencies
  .github/actions/run-tests/action.yml
  .github/workflows/checks.yml
  .golangci.yml
  Makefile
  cmd/root.go
  go.mod
  go.sum
  pkg/artifactcache/handler.go
  pkg/artifacts/arifacts_v4.go
  pkg/artifacts/server.go
  pkg/artifacts/server_test.go
  pkg/common/auth_test.go
  pkg/common/executor.go
  pkg/common/executor_test.go
  pkg/common/git/git_test.go
  pkg/container/container_types.go
  pkg/container/docker_build.go
  pkg/container/docker_cli.go
  pkg/container/docker_cli_test.go
  pkg/container/docker_images.go
  pkg/container/docker_images_test.go
  pkg/container/docker_network.go
  pkg/container/docker_pull.go
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/container/host_environment.go
  pkg/exprparser/interpreter.go
  pkg/model/action.go
  pkg/model/github_context.go
  pkg/model/github_context_test.go
  pkg/model/planner.go
  pkg/model/workflow.go
  pkg/model/workflow_test.go
  pkg/runner/action.go
  pkg/runner/action_test.go
  pkg/runner/expression.go
  pkg/runner/expression_test.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/reusable_workflow.go
  pkg/runner/run_context.go
  pkg/runner/run_context_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/runner/step_action_local.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote.go
  pkg/runner/step_action_remote_test.go
  pkg/runner/step_docker.go
  pkg/runner/step_docker_test.go
  pkg/runner/step_run.go
  pkg/runner/step_run_test.go
Labels: size/XL

#2540 fix: short sha has at least four digits
  pkg/common/git/git.go
Labels: size/XS

#2575 Enhance Install Script with Version Check and Force Install Option
  install.sh
Labels: size/M

#2502 fix: prevent unintended input replacement in reusable workflows with workflow_dispatch when using workflow_call
  pkg/runner/expression.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/.github/workflows/local-reusable-and-dispatch.yml
  pkg/runner/testdata/uses-workflow-defaults/workflow_dispatch.yml
Labels: size/M

#2590 Fix typo in `--action-offline-mode` option description
  cmd/root.go
Labels: needs-work, size/XS
