Repository nektos/act, pull requests merged in 2024-04, with the labels that each got.

#2288 Fix codecov in workflow
  .github/workflows/checks.yml
Labels: size/XS

#2284 Remove local action cache if remote has changed
  pkg/common/git/git.go
  pkg/common/git/git_test.go
Labels: kind/bug, size/M

#2279 chore: fix some comments
  pkg/runner/hashfiles/index.js
  pkg/runner/step_test.go
Labels: size/XS

#2274 fix: favor command-line flags over files
  cmd/root.go
Labels: size/XS

#2276 fix: skipped jobs have no result
  pkg/runner/run_context.go
Labels: size/XS

#2289 Bump docker to v26
  go.mod
  go.sum
  pkg/container/docker_run.go
Labels: needs-work, size/L, dependencies, go

#2293 Cross Pkg Coverage
  .github/actions/run-tests/action.yml
Labels: size/XS

#2296 Add codespell support (config, workflow to detect/not fix) and make it fix few typos
  .codespellrc
  .github/workflows/codespell.yml
  pkg/common/git/git.go
  pkg/container/docker_network.go
  pkg/runner/run_context.go
Labels: size/M
