Repository nektos/act, pull requests merged in 2024-07, with the labels that each got.

#2372 fix: make node tool non volatile
  pkg/runner/action.go
  pkg/runner/action_composite.go
  pkg/runner/action_test.go
  pkg/runner/expression.go
  pkg/runner/job_executor.go
  pkg/runner/job_executor_test.go
  pkg/runner/run_context.go
  pkg/runner/step_action_local_test.go
  pkg/runner/step_action_remote_test.go
Labels: size/M

#2373 fix: changed location of actrc in info message
  cmd/root.go
Labels: size/XS

#2355 fix: docker stub and add a test for this
  .github/workflows/checks.yml
  pkg/container/docker_stub.go
Labels: size/XS

#2394 Fix #2363. Add /pre- and /post-entrypoint handling
  pkg/model/action.go
  pkg/runner/action.go
Labels: size/L

#2248 build(deps): bump github.com/timshannon/bolthold to v0.0.0-20240314194003-30aac6950928
  go.mod
  go.sum
Labels: size/S

#2403 Bump mergo to v1.0.0 with new module URL
  go.mod
  go.sum
  pkg/container/docker_run.go
Labels: size/XS

#2405 remove double negation in --help
  cmd/root.go
Labels: size/XS
