Repository nektos/act, pull requests merged in 2024-02, with the labels that each got.

#2195 feat: correctly use the xdg library, which has the side effect to fix the config survey
  cmd/root.go
Labels: size/S

#2181 fix: Rootless error concerning `/var/run/docker.sock`
  cmd/root.go
  pkg/container/docker_socket.go
  pkg/container/docker_socket_test.go
Labels: size/L

#2173 feat: offline mode for new action cache
  cmd/root.go
  pkg/runner/action_cache_offline_mode.go
Labels: size/M

#2208 refactor: simplify go-git cache
  pkg/runner/action_cache.go
  pkg/runner/action_cache_test.go
Labels: size/L

#2155 feat: Test writing remote Actions locally
  cmd/input.go
  cmd/root.go
  pkg/runner/local_repository_cache.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/local-remote-action-overrides/config.yml
  pkg/runner/testdata/local-remote-action-overrides/push.yml
Labels: size/L

#2226 fix: logo and demo asset urls
  README.md
Labels: size/XS
