Repository nektos/act, pull requests merged in 2024-06, with the labels that each got.

#2350 Add riscv64 binary release
  .github/workflows/checks.yml
  .goreleaser.yml
Labels: size/XS

#2349 fix: update reusable workflow input handling
  pkg/model/workflow.go
  pkg/runner/expression.go
  pkg/runner/testdata/.github/workflows/local-reusable-workflow.yml
Labels: size/M

#2348 fix: composite action input pollution
  pkg/runner/action.go
  pkg/runner/runner_test.go
  pkg/runner/step.go
  pkg/runner/step_test.go
  pkg/runner/testdata/uses-composite-check-for-input-collision/action-with-pre-and-post/action.yml
  pkg/runner/testdata/uses-composite-check-for-input-collision/action-with-pre-and-post/main.js
  pkg/runner/testdata/uses-composite-check-for-input-collision/action-with-pre-and-post/post.js
  pkg/runner/testdata/uses-composite-check-for-input-collision/action-with-pre-and-post/pre.js
  pkg/runner/testdata/uses-composite-check-for-input-collision/composite_action/action.yml
  pkg/runner/testdata/uses-composite-check-for-input-collision/push.yml
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/action-with-pre-and-post/action.yml
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/action-with-pre-and-post/main.js
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/action-with-pre-and-post/post.js
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/action-with-pre-and-post/pre.js
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/composite_action/action.yml
  pkg/runner/testdata/uses-composite-check-for-input-shadowing/push.yml
Labels: size/L

#2281 fix: skip service container for empty image
  pkg/runner/run_context.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/services-empty-image/push.yaml
Labels: size/M
