Repository nektos/act, pull requests merged in 2025-02, with the labels that each got.

#2557 Detect available flags for extensions
  cmd/input.go
  cmd/notices.go
  cmd/root.go
Labels: needs-work, size/S

#2552 [BREAKING] refactor logger
  pkg/common/executor.go
  pkg/runner/job_executor.go
Labels: size/M

#2490 Incorporate Debug, Warn, Error logging.
  pkg/runner/command.go
Labels: size/XS

#2651 Use gh auth token for default GITHUB_TOKEN secret
  cmd/root.go
  pkg/gh/gh.go
  pkg/gh/gh_test.go
Labels: size/M

#2652 chore: remove comments from mergify on merge conflict or check failures
  .mergify.yml
Labels: size/XS

#2653 chore: move to environment secrets
  .github/workflows/checks.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .gitignore
Labels: size/M

#2664 fix: secret file reading
  cmd/root.go
  cmd/root_test.go
  cmd/testdata/secrets.yml
Labels: size/M

#2665 add test workflows to cmd pkg
  cmd/execute_test.go
  cmd/root.go
  cmd/root_test.go
Labels: size/L

#2673 chore: Group DependableBot Updates monthly
  .github/dependabot.yml
Labels: size/S

#2676 Update .gitleaksignore
  .gitleaksignore
Labels: size/XS

#2677 feat: GoGitActionCache shallow fetch
  pkg/runner/action_cache.go
Labels: size/XS

#2683 chore: mergify and codeowners do not request review
  .mergify.yml
  CODEOWNERS
Labels: size/S

#2682 Add tests against reading config files
  cmd/root_test.go
  cmd/testdata/env.actrc
  cmd/testdata/simple.actrc
  cmd/testdata/split.actrc
Labels: size/M

#2513 fix: remote docker actions new action cache and dry run mode
  pkg/container/docker_run.go
  pkg/container/docker_run_test.go
  pkg/runner/action.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/remote-action-docker-new-cache/config/config.yml
  pkg/runner/testdata/remote-action-docker-new-cache/push.yml
Labels: size/M

#2495 Disable "unable to get git repo" when none exists.
  pkg/model/github_context.go
Labels: size/XS

#2687 Clarify --no-skip-checkout flag
  cmd/root.go
Labels: size/XS
