Repository nektos/act, pull requests merged in 2025-03, with the labels that each got.

#2692 Refer to nektosact.com
  cmd/root.go
Labels: needs-work, size/XS

#2700 Report the elapsed time for each workflow step
  pkg/runner/step.go
Labels: size/XS

#2705 chore(deps): bump to go1.24 due to deps updates
  .github/workflows/checks.yml
  go.mod
Labels: size/XS

#2715 fix: reporting fetch failure as job error and log the error
  pkg/runner/job_executor.go
  pkg/runner/runner_test.go
  pkg/runner/testdata/action-cache-v2-fetch-failure-is-job-error/push.yml
Labels: size/L
